travis:
  secure:
    BINSTAR_TOKEN: RF/+jt1AVPJJdWJhO0zrthIOItHw9LeOmPR38tPnp/qQUOE9GW+xj2Q53M3ljoe3jwBLstIC9X+uvngLS0GGrT0qU8rkDSRe5Shk4d2WzZCEMVn7353bh40lZF0hWjGDVGeUIqXngSj6ZjH0RNTZDvy4vxo7KT11cn45xiuFkSZbr+0s8wfrclgOX4G273janZID+iNFJVO1zEsFcN0TL49xqPI9ox3SNK/1TpYIzbOCXJfq1xVQfcDKZmSnSnt4+0m/1yGy8wBlhySL25wSWWdI1HlFY+Oxtc7HieZixsSk1h4RIusZ/ISlNjNo83TLK2AmuYCGt1Lg9eIbrIYcocYc8hnFS8ZMS8zB+PcdvIcPadeH9L/UFFmdyrtff+iHqFuhyiPv/D9WOwKi77mvZjihTeRxfsoUIbVCTevptXamRrABfHc5bBriIMHA98lTQwFFp/EESx/X/P15VsSbV9HRgmtPV4T/OpuTEAFpAIuTGptHyMjuPHfmwIfVyYMuI77ccMXBFd75jtMfmF7H4/kS4HyYDPQvh+czvBjCtOx3Ay2VFj4qOa6FoW1x6S6aU2ECv2jCy/wt1SwcNNCu2p0c/tPjn5n1flkViGgYMSmb3K4H8VPVCvUIdxg7EBtijikPQ7ZFUXpbsYX1jjfZh0p5EfpPdgBYcmzUmbgBGBo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
